#!/usr/bin/env bash
# Grant a Steam account server admin.
#
#   bash bootstrap/add-admin.sh <steamid64> <display name> [immunity]
#
# Writes into CounterStrikeSharp's configs/admins.json, which is what
# CS2-SimpleAdmin reads its permissions from. '@css/root' grants everything;
# immunity 100 means lower-immunity admins cannot target you.
#
# Existing entries are preserved -- this merges, it does not overwrite.
set -euo pipefail
cd /mnt/c/Users/iveri/Documents/code/lantern/stack

STEAMID="${1:?steamid64 required}"
NAME="${2:?display name required}"
IMMUNITY="${3:-100}"

case "$STEAMID" in
  7656119*) : ;;
  *) echo "'$STEAMID' does not look like a SteamID64 (should start 7656119)"; exit 1 ;;
esac
[ "${#STEAMID}" -eq 17 ] || { echo "SteamID64 should be 17 digits, got ${#STEAMID}"; exit 1; }

UUID=$(docker compose exec -T panel php artisan tinker \
  --execute='echo \App\Models\Server::where("name","LANtern CS2")->value("uuid");' 2>/dev/null \
  | grep -oE '[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}' | head -1)
[ -n "$UUID" ] || { echo "could not resolve server uuid"; exit 1; }

VOL=/var/lib/pelican/volumes
CFG="game/csgo/addons/counterstrikesharp/configs/admins.json"
TMP=$(mktemp)

# Start from the existing file, or an empty object if this is the first admin.
if docker run --rm -v "$VOL":/v alpine test -f "/v/$UUID/$CFG"; then
  docker run --rm -v "$VOL":/v alpine cat "/v/$UUID/$CFG" > "$TMP"
  echo "existing admins.json ($(wc -c < "$TMP") bytes)"
else
  echo '{}' > "$TMP"
  echo "creating admins.json"
fi

OWNER=$(docker run --rm -v "$VOL":/v alpine \
        sh -c "stat -c '%u:%g' /v/$UUID/game/csgo/addons/counterstrikesharp/configs")

python3 - "$TMP" "$STEAMID" "$NAME" "$IMMUNITY" <<'PY'
import json, sys
path, steamid, name, immunity = sys.argv[1:5]

# CounterStrikeSharp may prepend a '// generated by...' header (JSONC).
with open(path, encoding='utf-8-sig') as f:
    raw = f.read()
lines = raw.splitlines(keepends=True)
header, body = [], lines
for i, line in enumerate(lines):
    if line.lstrip().startswith('//'):
        header.append(line)
    else:
        body = lines[i:]
        break
text = ''.join(body).strip() or '{}'
admins = json.loads(text)

# Replace any existing entry for this SteamID, whatever it is keyed under.
for key in [k for k, v in admins.items() if str(v.get('identity')) == steamid]:
    del admins[key]

admins[name] = {
    'identity': steamid,
    'immunity': int(immunity),
    'flags': ['@css/root'],
}

with open(path, 'w', encoding='utf-8') as f:
    f.writelines(header)
    json.dump(admins, f, indent=2)
    f.write('\n')

print(f'  admins now: {", ".join(admins.keys())}')
PY

docker run --rm -i -v "$VOL":/v alpine \
  sh -c "cat > /v/$UUID/$CFG && chown $OWNER /v/$UUID/$CFG" < "$TMP"
rm -f "$TMP"
echo "written (owner $OWNER)"
echo "Restart the server, or run 'css_reladmin' in the console, to apply."
