#!/usr/bin/env bash
# Write the WeaponPaints database credentials into its generated config.
#
# The config is created by CounterStrikeSharp on first plugin load, so this runs
# after the plugin has been enabled once. Only the Database* keys are touched --
# everything else the plugin generated is preserved.
set -euo pipefail
cd "$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")/.." || exit 1

CREDS=.weaponpaints-db
[ -f "$CREDS" ] || { echo "missing $CREDS -- run setup-weaponpaints-db.sh first"; exit 1; }
# shellcheck disable=SC1090
. "./$CREDS"

UUID=$(docker compose exec -T panel php artisan tinker \
  --execute='echo \App\Models\Server::where("name","LANtern CS2")->value("uuid");' 2>/dev/null \
  | grep -oE '[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}' | head -1)
[ -n "$UUID" ] || { echo "could not resolve server uuid"; exit 1; }

VOL=/var/lib/pelican/volumes
CFG="game/csgo/addons/counterstrikesharp/configs/plugins/WeaponPaints/WeaponPaints.json"
TMP=$(mktemp)

docker run --rm -v "$VOL":/v alpine cat "/v/$UUID/$CFG" > "$TMP"
echo "read config ($(wc -c < "$TMP") bytes)"

OWNER=$(docker run --rm -v "$VOL":/v alpine stat -c '%u:%g' "/v/$UUID/$CFG")

python3 - "$TMP" "$DB_HOST" "$DB_PORT" "$DB_NAME" "$DB_USER" "$DB_PASS" <<'PY'
import json, sys
path, host, port, name, user, pw = sys.argv[1:7]

# CounterStrikeSharp writes JSONC: a leading '// generated by...' header above
# the object. json.load chokes on it, so split the header off and put it back.
with open(path, encoding='utf-8-sig') as f:
    raw = f.read()
lines = raw.splitlines(keepends=True)
header, body = [], lines
for i, line in enumerate(lines):
    if line.lstrip().startswith('//'):
        header.append(line)
    else:
        body = lines[i:]
        break
cfg = json.loads(''.join(body))
cfg['DatabaseHost']     = host
cfg['DatabasePort']     = int(port)
cfg['DatabaseName']     = name
cfg['DatabaseUser']     = user
cfg['DatabasePassword'] = pw
with open(path, 'w', encoding='utf-8') as f:
    f.writelines(header)
    json.dump(cfg, f, indent=2)
    f.write('\n')
# Print the keys we set, with the password masked.
print('  DatabaseHost     =', host)
print('  DatabasePort     =', port)
print('  DatabaseName     =', name)
print('  DatabaseUser     =', user)
print('  DatabasePassword = <set,', len(pw), 'chars>')
PY

docker run --rm -i -v "$VOL":/v alpine sh -c "cat > /v/$UUID/$CFG && chown $OWNER /v/$UUID/$CFG" < "$TMP"
rm -f "$TMP"
echo "config written and ownership preserved ($OWNER)"
