// Create a Pelican client API key for the LANtern UI and write everything the
// UI backend needs to /tmp/lantern-ui.env inside the panel container.
//
// Written to a file rather than stdout so the key and RCON password never pass
// through a terminal or a transcript.

$user   = \App\Models\User::where('username', 'iveri')->first() ?? \App\Models\User::first();
$server = \App\Models\Server::where('name', 'LANtern CS2')->firstOrFail();

$memo = 'LANtern CS2 control UI';

// Reuse the existing key if one is already present -- the plaintext token is
// recoverable because Pelican stores it with an 'encrypted' cast, not a hash.
$key = \App\Models\ApiKey::where('user_id', $user->id)
    ->where('key_type', \App\Models\ApiKey::TYPE_ACCOUNT)
    ->where('memo', $memo)->first();

if (!$key) {
    $key = \App\Models\ApiKey::create([
        'user_id'     => $user->id,
        'key_type'    => \App\Models\ApiKey::TYPE_ACCOUNT,
        'identifier'  => \Illuminate\Support\Str::random(\App\Models\ApiKey::IDENTIFIER_LENGTH),
        'token'       => \Illuminate\Support\Str::random(32),
        'memo'        => $memo,
        'allowed_ips' => [],
        'permissions' => [],
    ]);
    $created = true;
} else {
    $created = false;
}

$full = $key->identifier . $key->token;

// RCON password lives in the server's variables.
$rconVar = $server->egg->variables()->where('env_variable', 'RCON_PASSWORD')->first();
$rcon = \App\Models\ServerVariable::where('server_id', $server->id)
    ->where('variable_id', $rconVar->id)->value('variable_value');

$alloc = $server->allocation;

$env = implode("\n", [
    '# Generated by create-ui-credentials.php. Gitignored -- do not commit.',
    'PELICAN_URL=http://192.168.0.115',  // Caddy matches on APP_URL host; 'panel' returns an empty 200
    'PELICAN_API_KEY=' . $full,
    'SERVER_UUID=' . $server->uuid,
    'SERVER_UUID_SHORT=' . $server->uuid_short,
    'RCON_HOST=' . ($alloc->ip_alias ?: $alloc->ip),
    'RCON_PORT=' . $alloc->port,
    'RCON_PASSWORD=' . $rcon,
    '',
]);

file_put_contents('/tmp/lantern-ui.env', $env);

echo ($created ? 'created' : 'reused') . " API key for {$user->username}" . PHP_EOL;
echo 'key length     : ' . strlen($full) . PHP_EOL;
echo 'rcon password  : ' . (strlen((string) $rcon) > 0 ? 'present (' . strlen($rcon) . ' chars)' : 'MISSING') . PHP_EOL;
echo 'server         : ' . $server->uuid_short . ' @ ' . $alloc->ip_alias . ':' . $alloc->port . PHP_EOL;
echo 'wrote /tmp/lantern-ui.env (values not printed)' . PHP_EOL;
