#!/bin/bash
# LANtern CS2 boot script. Runs on every server start.
#
# Three jobs:
#   1. Re-apply the Metamod patch to gameinfo.gi. steamcmd 'validate' REVERTS
#      this file on every update, which silently breaks all plugins -- so it
#      must be re-applied at boot, not just at install.
#   2. Activate only the plugin set the selected MODE needs. MatchZy, Retakes
#      and PracticeMode each hook round flow and produce broken rounds if two
#      are loaded at once.
#   3. Write the mode config and exec the server.

set -o pipefail
cd /home/container || exit 1

CSGO=/home/container/game/csgo
ADDONS="$CSGO/addons"
CSS="$ADDONS/counterstrikesharp"
STAGE="$CSS/plugins.available"
LIVE="$CSS/plugins"
CFG="$CSGO/cfg"

MODE="${MODE:-competitive}"
say() { echo "[LANtern] $*"; }

# ---------------------------------------------------- 1. gameinfo.gi (Metamod)
# Without 'Game csgo/addons/metamod' in SearchPaths, Metamod never loads and
# every plugin silently does nothing. Idempotent.
GAMEINFO="$CSGO/gameinfo.gi"
if [ -f "$GAMEINFO" ]; then
    if grep -q "csgo/addons/metamod" "$GAMEINFO"; then
        say "gameinfo.gi already patched for Metamod"
    else
        say "Patching gameinfo.gi for Metamod (reverted by the last CS2 update)"
        cp "$GAMEINFO" "$GAMEINFO.lantern.bak"
        awk '
            /Game_LowViolence/ && !done {
                match($0, /^[ \t]*/)
                print substr($0, 1, RLENGTH) "Game\tcsgo/addons/metamod"
                done = 1
            }
            { print }
        ' "$GAMEINFO.lantern.bak" > "$GAMEINFO"
        if grep -q "csgo/addons/metamod" "$GAMEINFO"; then
            say "  patched"
        else
            say "  WARNING: patch failed, restoring original -- plugins will not load"
            cp "$GAMEINFO.lantern.bak" "$GAMEINFO"
        fi
    fi
else
    say "WARNING: $GAMEINFO not found"
fi

# ------------------------------------------------------ 2. activate plugin set
# Sets are normalised at install time into csgo/-rooted overlays, each carrying
# a .lantern-plugins manifest of the plugin directories it owns. Activation is
# therefore: remove every plugin any set owns, then overlay the chosen sets.
if [ -d "$STAGE" ]; then
    # SimpleAdmin's dependency chain must load with it in every mode:
    # CS2-SimpleAdmin -> MenuManagerCS2 -> PlayerSettingsCS2 -> AnyBaseLibCS2
    SETS="anybaselib playersettings menumanager simpleadmin"
    [ "${ENABLE_SKINS:-0}" = "1" ] && SETS="$SETS weaponpaints"

    case "$MODE" in
        competitive) SETS="$SETS matchzy" ;;
        retakes)     SETS="$SETS retakes" ;;
        practice)    # CS2-Practice-Plugin v1.0.0.3 targets a 2024 CounterStrikeSharp
                     # and segfaults the server against current builds. Refuse
                     # rather than boot into a crash loop.
                     say "practice mode is disabled (CSPracc crashes current CS2); using competitive"
                     MODE=competitive; SETS="$SETS matchzy" ;;
        deathmatch)  ;;                                   # vanilla DM, admin only
        *)           say "Unknown MODE '$MODE', falling back to competitive"
                     MODE=competitive; SETS="$SETS matchzy" ;;
    esac

    say "MODE=$MODE -> activating: $SETS"
    mkdir -p "$LIVE"

    # Deactivate everything first. Removing only what the manifests claim means
    # we never delete a plugin a user dropped in by hand.
    for s in "$STAGE"/*/; do
        m="${s}.lantern-plugins"
        [ -f "$m" ] || continue
        while IFS= read -r p; do
            [ -n "$p" ] && rm -rf "${LIVE:?}/$p"
        done < "$m"
    done

    for s in $SETS; do
        if [ -d "$STAGE/$s" ]; then
            cp -a "$STAGE/$s/." "$CSGO"/ 2>/dev/null && say "  + $s"
        else
            say "  ! $s not staged, skipping"
        fi
    done
    rm -f "$CSGO/.lantern-plugins"        # manifest is metadata, not game content

    say "active plugins: $(ls -1 "$LIVE" 2>/dev/null | tr '\n' ' ')"
else
    say "No staged plugins found -- running vanilla"
fi

# --------------------------------------------------------- 3. mode config file
mkdir -p "$CFG"
{
    echo "// Generated by LANtern on every boot. Do not edit -- edit the egg."
    echo "sv_lan 1"
    echo "sv_cheats 0"
    echo "hostname \"${SERVER_NAME:-LANtern CS2}\""
    echo "sv_hibernate_when_empty 0"
    echo "bot_quota_mode fill"
    echo "bot_quota ${BOT_QUOTA:-10}"
    echo "bot_difficulty ${BOT_DIFFICULTY:-2}"
    echo "mp_autoteambalance 1"
    echo "mp_limitteams 2"
    # Credentials go in the config, never on the command line: CounterStrikeSharp
    # echoes the full argv at startup, which would print them into the container
    # log and anything that reads it.
    [ -n "${RCON_PASSWORD:-}" ]   && echo "rcon_password \"${RCON_PASSWORD}\""
    [ -n "${SERVER_PASSWORD:-}" ] && echo "sv_password \"${SERVER_PASSWORD}\""
    case "$MODE" in
        competitive)
            echo "mp_maxrounds 24"; echo "mp_overtime_enable 1"
            echo "mp_warmuptime 60"; echo "mp_freezetime 15"
            echo "tv_enable 1"; echo "tv_autorecord 1"; echo "tv_delay 30"
            ;;
        retakes)
            echo "mp_maxrounds 0"; echo "mp_freezetime 3"; echo "mp_warmuptime 10"
            echo "tv_enable 0"
            ;;
        practice)
            echo "sv_cheats 1"; echo "mp_limitteams 0"; echo "mp_autoteambalance 0"
            echo "mp_maxmoney 65535"; echo "mp_startmoney 65535"
            echo "mp_buytime 60000"; echo "mp_buy_anywhere 1"
            echo "mp_roundtime 60"; echo "mp_freezetime 0"; echo "sv_infinite_ammo 1"
            echo "bot_quota 0"; echo "tv_enable 0"
            ;;
        deathmatch)
            echo "mp_maxrounds 0"; echo "mp_freezetime 0"; echo "tv_enable 0"
            ;;
    esac
} > "$CFG/lantern.cfg"
say "Wrote $CFG/lantern.cfg"

# ------------------------------------------------------------------ 4. launch
case "$MODE" in
    deathmatch) GT=1; GM=2 ;;
    *)          GT=0; GM=1 ;;
esac

ARGS=(
    -dedicated
    -ip 0.0.0.0
    -port "${SERVER_PORT}"
    -maxplayers "${MAX_PLAYERS:-12}"
    +game_type "$GT"
    +game_mode "$GM"
    +map "${SRCDS_MAP:-de_dust2}"
    +exec lantern.cfg
)
[ "${VAC_ENABLED:-0}" = "1" ] || ARGS+=(-insecure)
[ "${RCON_ENABLED:-1}" = "0" ] || ARGS+=(-usercon)
[ -n "${TV_PORT}" ]        && ARGS+=(-tv_port "${TV_PORT}")
# rcon_password and sv_password are deliberately NOT passed here -- they are
# written into lantern.cfg above so they never appear in argv or the log.
# Only pass a GSLT if one is actually set; sv_lan 1 does not need one.
[ -n "${STEAM_GSLT}" ]     && ARGS+=(+sv_setsteamaccount "${STEAM_GSLT}")

say "Launching CS2 (mode=$MODE, game_type=$GT, game_mode=$GM, port=${SERVER_PORT})"
export LD_LIBRARY_PATH="/home/container/game/bin/linuxsteamrt64:$LD_LIBRARY_PATH"
exec ./game/bin/linuxsteamrt64/cs2 "${ARGS[@]}"
